name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/react-autodeploy:set1 
                
            - name: Deploy to Play with Docker
              run: |
                sshpass -p "${{ secrets.PWD_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.PWD_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME}}/react-autodeploy:set1 && 
                docker stop devcontainer || true &&
                docker rm devcontainer || true &&
                docker run -d -p 80:80 --name devcontainer ${{ secrets.DOCKER_USERNAME }}/react-autodeploy:set1"
                